### ISSUE TITLE
关于traffic中的单位问题。

### ISSUE THREAD

**Issue by zouri** [alibaba/tsar#106]

**Comment by zouri** [comment]
![图片](https://user-images.githubusercontent.com/21356211/90355733-d22f3900-e07f-11ea-966d-6b3ea6a1c434.png)

![图片](https://user-images.githubusercontent.com/21356211/90355785-fb4fc980-e07f-11ea-96f1-33bbaf42ec60.png)
1. tsar 单位问题
请问你们这个tsar中traffic中的M，K是什么意思，是数字单位千和兆，还是数据单位mb和kb的意思？

2. 网络流量数据统计差异问题
关于 sar 和 tsar 中，数据差异较大，我们的机器是2块 eth 开头的网卡进行绑定在一起，绑成 bond0，但是发现 sar 中统计 bond0 的流量远大于 tsar  统计的流量，按照 tsar 中 readme 介绍 traffic 统计的流量是统计 eth 和 em 开头的网卡的所有流量，为什么会有这么大的数据差异

**Comment by kongjian** [comment]
1、这里的M和K都是1024进制，如果想看详细数据，可以通过--detail来看
2、tsar采集网卡只采集特殊网卡，会做一些过滤，这里面可能是内网东西向流量较大导致

**Comment by zouri** [comment]
谢谢你的回复
