### ISSUE TITLE
output_print.c:343 fgets error:Success

### ISSUE THREAD

**Issue by Lowpower** [alibaba/tsar#58]
tsar --cpu

**Comment by harryshayne** [comment]
yeah，I got this too.

**Comment by xkking** [comment]
caused by issue of tsar.data.

**Comment by kongjian** [comment]
please check if tsar -l run correct.
then check your crond, if the proc exists,check /var/log/tsar.data file last modify time.
you can delete the /var/log/tsar.data* to solve the problem

**Comment by caihanze** [comment]
tsar -l 输出正常。delete the /var/log/tsar.data* 后tsar出错信息更改为：output_print.c:626 unable to open the log file /var/log/tsar.data

**Comment by johnlcd** [comment]
遇到相同问题，如何解决呢？

**Comment by z21921** [comment]
遇到相同问题，如何解决呢？

**Comment by Jolin-blank** [comment]
将/etc/cron.d/tsar的文件权限修改为644
