### ISSUE TITLE
mac上不能跑

### ISSUE THREAD

**Issue by shijinkui** [alibaba/tsar#61]
$ sudo tsar -li 1
[Wed Apr  8 21:51:36 2015] framework.c:66 load_modules: dlopen module mod_io err dlopen(/usr/local/tsar/modules/mod_io.so, 10): image not found
[Wed Apr  8 21:51:36 2015] framework.c:66 load_modules: dlopen module mod_partition err dlopen(/usr/local/tsar/modules/mod_partition.so, 10): image not found
Time              ---cpu-- ---mem-- ---tcp-- -----traffic---- ---load-
Time                util     util   retran    bytin  bytout    load1
08/04/15-21:51:37 ------   ------   ------   ------  ------   ------
08/04/15-21:51:38 ------   ------   ------   ------  ------   ------
08/04/15-21:51:39 ------   ------   ------   ------  ------   ------

**Comment by kongjian** [comment]
因为采集方式差异较大 目前没有支持mac
主要支持的是linux内核,后续会做一些跨平台支持
