### ISSUE TITLE
centos5.8 64位编译报错

### ISSUE THREAD

**Issue by liudotman** [alibaba/tsar#62]
for i in modules src; do make -C $i; done
make[1]: Entering directory `/home/software/star/tsar-master/modules'
gcc -I../include -Wall -fPIC --shared -g -O2 -Wno-strict-aliasing mod_swap.c -o mod_swap.so
/usr/bin/ld: cannot open output file mod_swap.so: No such file or directory
collect2: ld 返回 1
make[1]: *** [mod_swap.so] 错误 1
make[1]: Leaving directory`/home/software/star/tsar-master/modules'
make[1]: Entering directory `/home/software/star/tsar-master/src'
gcc config.o debug.o framework.o tsar.o output_file.o output_print.o output_db.o output_tcp.o output_nagios.o common.o -o tsar -I../include -g -Wall -ldl -rdynamic
/usr/bin/ld: cannot open output file tsar: No such file or directory
collect2: ld 返回 1
make[1]: *** [tsar] 错误 1
make[1]: Leaving directory`/home/software/star/tsar-master/src'
make: **\* [all] 错误 2

**Comment by kongjian** [comment]
看起来是/usr/bin/ld:的问题，可以看一下系统里面这个ld为什么不存在
另外tsar内部只在redhat上使用
