### ISSUE TITLE
io 采集的util 是如何计算出来的？ 

### ISSUE THREAD

**Issue by zyx19855** [alibaba/tsar#67]
io 采集的util 是如何计算出来的？

**Comment by kongjian** [comment]
https://github.com/alibaba/tsar/blob/master/info.md

**Comment by zyx19855** [comment]
st_array[10] = ticks / (inter * 10.0); /* percentage! */
 (inter * 10.0) 这个表示的是什么意思?

**Comment by kongjian** [comment]
/1000 *100 = /10单位转化成s,并且是百分比

**Comment by zyx19855** [comment]
了解,谢谢....
