### ISSUE TITLE
和nginx集成不成功，全是横线

### ISSUE THREAD

**Issue by lep2015** [alibaba/tsar#72]
根据官方教程进行安装并配置nginx，运行curl 127.0.0.1:80/nginx_status出现
Active connections: 14 
server accepts handled requests
 628 628 837 
Reading: 0 Writing: 3 Waiting: 11 
但是运行curl 127.0.0.1:80/nginx_status -H 'Host: status.taobao.com'出错，404
运行tsar --nginx --live -i 1的时候全是横线
Time           ----------------------------------nginx--------------------------------- 
Time           accept  handle    reqs  active    read   write    wait     qps      rt  
08/07/16-17:00 ------  ------  ------  ------  ------  ------  ------  ------  ------  
08/07/16-17:05 ------  ------  ------  ------  ------  ------  ------  ------  ------  
08/07/16-17:10 ------  ------  ------  ------  ------  ------  ------  ------  ------  
08/07/16-17:15 ------  ------  ------  ------  ------  ------  ------  ------  ------  
08/07/16-17:20 ------  ------  ------  ------  ------  ------  ------  ------  ------  
08/07/16-17:25 ------  ------  ------  ------  ------  ------  ------  ------  ------  
08/07/16-17:30 ------  ------  ------  ------  ------  ------  ------  ------  ------   

求大神指教

**Comment by xkking** [comment]
status.taobao.com 配置了server但是里边没有配置nginx_status？

**Comment by lep2015** [comment]
我看文档里面说-H的参数是status.taobao.com，您的意思是这个参数是我自己的站点？在哪儿配置呢？

**Comment by AstroProfundis** [comment]
我记得只要访问 http://localhost/ngnix_status 有东西就可以了

**Comment by chobits** [comment]
> 我看文档里面说-H的参数是status.taobao.com，您的意思是这个参数是我自己的站点？在哪儿配置呢？

nginx server{}中（配置 stub_status指令的）需要添加server_name status.taobao.com;，用于支持Host为 status.taobtao.com的请求服务

**Comment by kongjian** [comment]
在nginx的配置文件中，可以配置成如下，如果不想用status.taobao.com，配置成localhost也可以
    server {
        listen              80;
        server_name         status.taobao.com;
        location            = /nginx_status {
            stub_status     on;
        }
    }
