### ISSUE TITLE
framework.c:454: error: conflicting types for ‘read_line_to_module_record’

### ISSUE THREAD

**Issue by jxzkin** [alibaba/tsar#80]

**Comment by leafyongzhong** [comment]
https://github.com/kongjian/tsar/commit/625d51d407dc293caf61575586452f5d79fdbdd8
这次的commit直接把read_line_to_module_record的类型改掉了,导致的make error

**Comment by kongjian** [comment]
好的 我们处理一下

**Comment by lilymona** [comment]
已修复，抱歉
