### ISSUE TITLE
parse_add_string

### ISSUE THREAD

**Issue by guoyunliang** [alibaba/tsar#84]
if (var == NULL) {
        if (token) {
            strncpy(var, token, strlen(token));
        }
    } else {
        if (token) {
            strcat(token, ",");
            strncat(token, var, strlen(var));
        }
        if (token) {
            strncpy(var, token, strlen(token));
        }
    }
上述代码中，var==NULL时，怎么还可以执行strncpy

**Comment by kongjian** [comment]
这是错误用法 目前代码走不到这个分支 但是需要修复
